---
# Install splunk 
#
#
- name: Copy server.conf for splunk 
  template: src=server.conf dest="{{ splunk_home }}/etc/system/local/server.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  register: server_conf

- name: Add master-apps
  unarchive: src=master-apps.tgz dest="{{ splunk_home }}/etc/master-apps"
  become: yes
  become_user: "{{ splunk_user }}"
  register: ma

- name: Deploy bundle to cluster peers
  command: "{{ splunk_home }}/bin/splunk apply cluster-bundle --answer-yes -auth {{ splunk_user }}:{{ splunk_admin_pass }}"
  become: yes
  become_user: "{{ splunk_user }}"

- name: Add outputs.conf
  template: src=outputs.conf dest="{{ splunk_home }}/etc/system/local/outputs.conf" mode=660
  become: yes
  become_user: "{{ splunk_user }}"
  register: outputs

- name: Copy web.conf for splunk 
  template: src=web.conf dest="{{ splunk_home }}/etc/system/local/web.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  register: web_conf

- name: Copy init script to init.d
  template: src=splunk_init dest="/etc/init.d/splunk-{{ splunk_role }}" mode=700
  become: yes
  register: init

- name: Generate init symlinks
  command: "/sbin/chkconfig splunk-{{ splunk_role }} --add"
  become: yes

- name: Set init runlevels
  command: "/sbin/chkconfig splunk-{{ splunk_role }} on --level 235"
  become: yes

- name: Restart splunk 
  service: name="splunk-{{ splunk_role }}" state=restarted enabled=yes 
  become: yes
  when: (outputs.changed or server_conf.changed or init.changed or web_conf.changed)

