---
# Install splunk 
#
#
- name: Set server.conf configs (general.site)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: general
    option: site
    value: "{{ splunk_cluster_site }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.multisite)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: clustering
    option: multisite
    value: "{{ splunk_cluster_multisite }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.site_replication_factor)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: clustering
    option: site_replication_factor
    value: "{{ splunk_site_replication_factor }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.site_search_factor)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: clustering
    option: site_search_factor
    value: "{{ splunk_site_search_factor }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.available_sites)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: clustering
    option: available_sites
    value: "{{ splunk_available_sites }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.forwarder_site_failover)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: clustering
    option: forwarder_site_failover
    value: "{{ splunk_forwarder_site_failover }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

