---
# common defaults

pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCMSfYuG2qpu8msYIeGJipbjS8hhzBXNkzJT52wgl3e+g+sHrVkUbzMbbS2SXVFbaQefJ9YWDremK5JI+YVoBwUHWUXXOV9HaJuq2FYVEjAUQ4GXVmRqtiXO2U22hSK3d3b1CCHCZcr0gbrpsHioKzwdVGY5V0Jv/CbWrxVRlYFH5FUn/ZkWEeID4UyqB7EWRd2h8MIWzbqeIomLRbLMPOWheRqI1PIzrM/20/hqiLZIChMfuI0OMTZbFGFaqtUEbEkrVpf36fOQwaeTtmOsMc00ZIY3uDMUyk1jjdPBoNidRXkZn+mrrHH5WFffrYH46Jtg0qhmUXlnK3NjADjj0BP jay_splunk"

