- name: Check for existing pass4SymmKey and don't set it again.
  command: "cat {{ splunk_home }}/etc/system/local/server.conf"
  register: keyCheck
  become: true
  become_user: "{{ splunk_user }}"
  changed_when: false

- name: Add search peers (cluster master & DS)
  command: "{{ splunk_home }}/bin/splunk add search-server https://{{ hostvars[item].ec2_private_dns_name }}:8089 -auth admin:{{ splunk_admin_pass }} -remoteUsername admin -remotePassword {{ splunk_admin_pass }}"
  with_items:
    - "{{ groups['cluster_master'] }}"
    - "{{ groups['deployment_servers'] }}"
  become: yes
  become_user: "{{ splunk_user }}"
  ignore_errors: true
  when: ( splunk_idx_clustering == true )
  changed_when: false
  no_log: true

- name: Set server.conf configs (clustering.pass4SymmKey)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    section: clustering
    option: pass4SymmKey
    value: "{{ splunk_idx_clustering_key }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
#  when: keyCheck.stdout.find('pass4SymmKey') == -1
  no_log: true
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.mode)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    section: clustering
    option: mode
    value: "{{ splunk_idx_clustering_mode }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.cluster_label)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    section: clustering
    option: cluster_label
    value: "{{ splunk_idx_clustering_label }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (clustering.master_uri)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    section: clustering
    option: master_uri
    value: "{{ splunk_cm_uri }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs ([replication_port://9887])
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    section: replication_port://9887
    option: disabled
    value: false
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

