---
- name: Add search peers
  command: "{{ splunk_home }}/bin/splunk add search-server https://{{ hostvars[item].ec2_private_dns_name }}:8089 -auth admin:{{ splunk_admin_pass }} -remoteUsername admin -remotePassword {{ splunk_admin_pass }}"
  with_items:
    - "{{ groups['indexers'] }}"
  become: yes
  become_user: "{{ splunk_user }}"
  ignore_errors: true
  register: add_peer_results

- name: Check add-peer results
  fail:
    msg: "Add peer failed: {{ item.stderr }}"
  when: item.rc != 0 and item.rc != 24
  with_items: "{{ add_peer_results.results }}"

- name: Copy server.conf for splunk 
  template: src=server.conf dest="{{ splunk_home }}/etc/system/local/server.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  register: server_conf

- name: Copy web.conf for splunk 
  template: src=web.conf dest="{{ splunk_home }}/etc/system/local/web.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  register: web_conf

- name: Copy init script to init.d
  template: src=splunk_init dest="/etc/init.d/splunk-{{ splunk_role }}" mode=700
  become: yes
  register: init

- name: Generate init symlinks
  command: "/sbin/chkconfig splunk-{{ splunk_role }} --add"
  become: yes

- name: Set init runlevels
  command: "/sbin/chkconfig splunk-{{ splunk_role }} on --level 235"
  become: yes

- name: Restart splunk 
  service: name="splunk-{{ splunk_role }}" state=restarted enabled=yes 
  become: yes
  when: (server_conf.changed or init.changed or web_conf.changed)
