---
# Install splunk 
#
#
- name: Set server.conf configs (general.site)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: general
    option: site
    value: "{{ splunk_cluster_site }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

