---
- hosts: all
  become: yes
  roles:
    - common

- hosts: deployment_servers
  become: no
  roles:
  - ds

- hosts: cluster_master
  become: no
  roles:
  - cm

- hosts: indexers
  become: no
  roles:
  - idx

- hosts: search_heads
  become: no
  roles:
  - sh

- hosts: universal_forwarders
  become: no
  roles:
  - uf

- hosts: clients
  become: no
  roles:
  - uf


