---
- hosts: all
  become: yes
  roles:
    - common

- hosts: deployment_servers
  become: no
  roles:
  - ds

- hosts: cluster_master
  become: no
  roles:
  - cm

- hosts: indexers
  become: no
  roles:
  - idx
  - idx_cluster_member

- hosts: search_heads
  become: no
  roles:
  - sh
  - idx_cluster_member

- hosts: universal_forwarders
  become: no
  roles:
  - uf

- hosts: clients
  become: no
  roles:
  - uf


