---
# Install the UF (opt splunk should already exist) 
#
#

- name: Check for existing UF repo.
  stat: path="{{ splunk_home }}/.git"
  register: st
  ignore_errors: True

- include: upgrade.yml
  when: st.stat.isdir is defined

- include: install.yml
  when: st.stat.isdir is not defined
