---
- name: Set web.conf configs (settings.startwebserver)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/web.conf" 
    section: settings
    option: startwebserver
    value: "{{splunk_web_enabled}}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set web.conf configs (settings.mgmtHostPort) 
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/web.conf" 
    section: settings
    option: mgmtHostPort
    value: "0:{{splunkd_mgmt_port}}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (general.serverName)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    section: general
    option: serverName
    value: "{{ splunk_role }}-{{ inventory_hostname }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs (kvstore.disabled)
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    section: kvstore
    option: disabled
    value: "{{ splunk_kvstore_disabled }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Configure license slave
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: license
    option: master_uri
    value: "{{ splunk_lm_uri }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  when: (splunk_lm_uri is defined)

