---
- name: Reload systemd
  systemd: daemon_reload=yes
  become: yes

- name: Enable collectd
  systemd:
    name: collectd
    enabled: yes
    masked: no
  become: yes

- name: Start collectd
  systemd:
    name: collectd
    state: started
  become: yes

- name: Restart collectd
  systemd:
    name: collectd
    state: restarted
  become: yes

- name: Stop collectd
  systemd:
    name: collectd
    state: stopped
  become: yes

