---
- name: Install collectd service
  copy:
    src: "{{ collectd_home }}/contrib/collectd.service"
    remote_src: no
    dest: "/etc/systemd/system/collectd.service"
    mode: 644
  become: yes
  notify:
    - Reload systemd

- name: Reload systemd
  systemd: daemon_reload=yes
  become: yes

- name: Enable collectd
  systemd:
    name: collectd
    enabled: yes
    masked: no
  become: yes

- name: Start collectd
  systemd:
    name: collectd
    state: started
  become: yes

- name: Restart collectd
  systemd:
    name: collectd
    state: reloaded
  become: yes

- name: Stop collectd
  systemd:
    name: collectd
    state: reloaded
  become: yes

