---
# Install splunk 
#
#

- name: Check for existing splunk home"
  stat: path="{{ splunk_home }}"
  register: path
  become: yes

- name: Stop splunk if running
  command: "{{ splunk_home }}/bin/splunk stop"
  ignore_errors: True
  become: yes
  become_user: "{{ splunk_user }}"
  when: path.stat.isdir is defined

- name: Remove old dir
  file: path={{ splunk_home }} state=absent
  when: path.stat.isdir is defined
  become: yes

- name: Chmod and Chown shit.
  file: dest={{ splunk_root }} owner={{ splunk_user }} group={{ splunk_group }} 
  become: yes

- name: Checkout Latest Splunk bits from Git
  git: repo={{ splunk_git_repo }} dest={{ splunk_home }} ssh_opts="-o StrictHostKeyChecking=no" force=yes
  become: yes
  become_user: "{{ splunk_user }}"

- name: Copy init script to init.d
  template: src=splunk_init dest="/etc/init.d/splunk-{{ splunk_role }}" mode=755
  become: yes

- name: Generate init symlinks
  command: "/sbin/chkconfig splunk-{{ splunk_role }} --add"
  become: yes

- name: Set init runlevels
  command: "/sbin/chkconfig splunk-{{ splunk_role }} on --level 235"
  become: yes

- name: Start Splunk
  command: "{{ splunk_home }}/bin/splunk start --accept-license --no-prompt --answer-yes"
  become: yes
  become_user: "{{ splunk_user }}"

- name: Set splunk admin password
  command: "{{ splunk_home }}/bin/splunk edit user admin -password {{ splunk_admin_pass }} -auth admin:changeme"
  become: yes
  become_user: "{{ splunk_user }}"

