---
# Install splunk 
#
#

- name: Check for existing repo.
  stat: path="{{ splunk_home }}/.git"
  register: st
  ignore_errors: true
  become: true

- include: install.yml
  when: st.stat.isdir is not defined

- name: Ensure SPLUNK_OS_USER is set
  lineinfile: dest="{{ splunk_home }}/etc/splunk-launch.conf" 
              state=present 
              line="SPLUNK_OS_USER={{ splunk_user }}"
  become: true
  become_user: "{{ splunk_user }}"
 
