---
# Install splunk 
#
#

- name: Check for existing splunk root dir.
  stat: path="{{ splunk_root }}"
  register: st
  ignore_errors: true
  become: true

- include: install.yml
  when: st.stat.isdir is not defined

- name: Ensure SPLUNK_OS_USER is set
  lineinfile: dest="{{ splunk_home }}/etc/splunk-launch.conf" 
              state=present 
              line="SPLUNK_OS_USER={{ splunk_user }}"
  become: true
  become_user: "{{ splunk_user }}"
 
- name: Chmod and Chown shit.
  file: dest={{ splunk_root }} owner={{ splunk_user }} group={{ splunk_group }} recurse=yes
  become: yes

