---
# Upgrade splunk 
#
# Should really change this to do a version check vs a hard down / checkout...should be simple with Git dumbass

- name: Ensure splunk is stopped prior to upgrade
  command: "{{ splunk_home }}/bin/splunk stop"
  ignore_errors: True

- name: Chmod and Chown shit.
  file: dest={{ splunk_root }} owner={{ splunk_user }} group={{ splunk_group }} recurse=yes
  become: yes

- name: Checkout Latest Splunk from Git
  git: repo={{ splunk_git_repo }} dest={{ splunk_home }} accept_hostkey=yes force=yes
  become: true
  become_user: "{{ splunk_user }}"

- name: Copy web.conf for splunk
  template: src=web.conf dest="{{ splunk_home }}/etc/system/local/web.conf" mode=650
  become: true
  become_user: "{{ splunk_user }}"

- name: Start splunk 
  command: "{{ splunk_home }}/bin/splunk start --accept-license --answer-yes --no-prompt"
  become: true
  become_user: "{{ splunk_user }}"

