---
# Initial server setup.  Calls includes where needed.
#

- name: Install Git
  yum: name=git state=present
  become: yes
  
- name: Update root pub/auth keys 
  lineinfile: dest=~/.ssh/authorized_keys line="{{ pubkey }}" state=present create=yes mode=0400
  become: yes

- name: Update root priv key
  copy: src=id_rsa backup=yes mode=0400 dest=~/.ssh/id_rsa
  become: yes

- name: Update root known_hosts
  copy: src=known_hosts backup=yes mode=0400 dest=~/.ssh/known_hosts
  become: yes

- name: Update pub/auth keys 
  lineinfile: dest=~/.ssh/authorized_keys line="{{ pubkey }}" state=present create=yes mode=0400

- name: Update known_hosts
  copy: src=known_hosts backup=yes mode=0400 dest=~/.ssh/known_hosts

- name: Update priv key
  copy: src=id_rsa backup=yes mode=0400 dest=~/.ssh/id_rsa
