---
# Initial server setup.  Calls includes where needed.
#

- name: Install some pre-req packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - sysstat
  become: yes
  
- name: Update root pub/auth keys 
  lineinfile: dest=~/.ssh/authorized_keys line="{{ pubkey }}" state=present create=yes mode=0400
  become: yes

- name: Update root priv key
  copy: src=id_rsa backup=yes mode=0400 dest=~/.ssh/id_rsa
  become: yes

- name: Update pub/auth keys 
  lineinfile: dest=~/.ssh/authorized_keys line="{{ pubkey }}" state=present create=yes mode=0400

- name: Update priv key
  copy: src=id_rsa backup=yes mode=0400 dest=~/.ssh/id_rsa

- name: Create splunk group
  group: name="{{ splunk_group }}" gid="{{ splunk_gid }}" state=present
  become: yes

- name: Create splunk user
  user: name="{{ splunk_user }}" 
        state=present 
        comment="Splunk User account" 
        uid="{{ splunk_uid }}" 
        group="{{ splunk_group }}" 
        move_home=yes 
        home="{{ splunk_root }}"
  become: yes

- name: Create and Chown shit.
  file: dest={{ splunk_root }} owner={{ splunk_user }} group={{ splunk_group }} state=directory recurse=true
  become: yes

- name: Update splunk user pub/auth keys 
  lineinfile: dest="{{ splunk_root }}/.ssh/authorized_keys" line="{{ pubkey }}" state=present create=yes mode=0400
  become: yes

- name: Update splunk user priv key
  copy: src=id_rsa backup=yes mode=0400 dest="{{ splunk_root }}/.ssh/id_rsa" owner="{{ splunk_user }}" group="{{ splunk_group }}"
  become: yes

- name: Create directory for ansible custom facts
  file: state=directory recurse=yes path=/etc/ansible/facts.d 
  become: yes

- name: install custom splunk fact
  copy: src=splunk.fact dest=/etc/ansible/facts.d mode=755
  become: yes

- name: re-read facts after adding custom fact
  setup: filter=ansible_local
  become: yes

