---
# Initial server setup.  Calls includes where needed.
#

- name: Install some pre-req packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - sysstat
  become: yes
  
- name: Update root pub/auth keys 
  authorized_key:
    user: root
    key: "{{ pubkey }}" 
    state: present 
  no_log: true
  become: yes

- name: Update root priv key
  copy: 
    backup: yes 
    dest: ~/.ssh/id_rsa
    content: "{{ privkey }}"
    mode: 0600
  no_log: true
  become: yes

- name: Create splunk group
  group: name="{{ splunk_group }}" gid="{{ splunk_gid }}" state=present
  become: yes

- name: Create splunk user
  user: name="{{ splunk_user }}" 
        state=present 
        comment="Splunk User account" 
        uid="{{ splunk_uid }}" 
        group="{{ splunk_group }}" 
        move_home=yes 
        home="{{ splunk_root }}"
  become: yes

- name: Create and Chown shit.
  file: dest={{ splunk_root }} owner={{ splunk_user }} group={{ splunk_group }} state=directory recurse=true
  become: yes

- name: Update splunk user pub/auth keys 
  authorized_key:
    user: "{{ splunk_user }}"
    key: "{{ pubkey }}" 
    state: present 
  become: yes

- name: Update splunk user priv key
  copy: 
    backup: yes 
    dest: ~/.ssh/id_rsa
    content: "{{ privkey }}"
    mode: 0600
  no_log: true
  become: yes
  become_user: "{{ splunk_user }}"


- name: Create directory for ansible custom facts
  file: state=directory recurse=yes path=/etc/ansible/facts.d 
  become: yes

- name: install custom splunk fact
  copy: src=splunk.fact dest=/etc/ansible/facts.d mode=755
  become: yes

- name: re-read facts after adding custom fact
  setup: filter=ansible_local
  become: yes

