---
# splunk server roles

# splunk User stuff
splunk_uid: 70063
splunk_gid: 200024
splunk_base: /opt/splunk
splunk_pw: fds4Xy_36y{FfF5zk
splunk_uf_ds: chapda3logi09.ops.tiaa-cref.org:8089
splunk_pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEApqGiYMRbaNSdOcxTmmF5e2A0lz6wig2275zSDic7iW+0nJbbovbzof+S3un+BLvYPg5ux8KihkVJt0A+HUpB6Latpw5QaYYk2vNJL1moWOBaJrICAiAOJk7kewazBjEsPE/mWS7XWNhp1Gax+P6NbgApSN7y9zUEZd/mCn+LQl5tsHN7fAcUOITzfght0arlxbB18JD76qL3c1+C53Twwq9YSb+G8F4MElHVow9TNn4ZFNntra2dzSSQ34ZjfKZiju39ovrhvXlFi8qhp/F5e0XZEM6hIdBmtjAQDy3KO8skr8+Dlb7RiqRku8sb1clASST9jOsf8YvMdGlyUaclQQ== splunk@denpdb3utlog02"

# Disks 
splunk_base_device: /dev/sdb1
 
