---
- name: Create app structure for deployment-apps.
  file: dest="{{ splunk_home }}/etc/deployment-apps/jks_outputs/local" mode=750 state=directory recurse=yes
  become: yes
  become_user: "{{ splunk_user }}"

- name: Add outputs.conf
  template: src=outputs.conf dest="{{ splunk_home }}/etc/deployment-apps/jks_outputs/local/outputs.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Add serverclasses
  unarchive: src=apps.tgz dest="{{ splunk_home }}/etc/apps/"
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Add deployment-apps
  unarchive: src=deployment-apps.tgz dest="{{ splunk_home }}/etc/deployment-apps"
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy outputs.conf for splunk
  template: src=outputs.conf dest="{{ splunk_home }}/etc/system/local/outputs.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy server.conf for splunk 
  template: src=server.conf dest="{{ splunk_home }}/etc/system/local/server.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy web.conf for splunk 
  template: src=web.conf dest="{{ splunk_home }}/etc/system/local/web.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy init script to init.d
  template: src=splunk_init dest="/etc/init.d/splunk-{{ splunk_role }}" mode=755
  become: yes

- name: Generate init symlinks
  command: "/sbin/chkconfig splunk-{{ splunk_role }} --add"
  become: yes

- name: Set init runlevels
  command: "/sbin/chkconfig splunk-{{ splunk_role }} on --level 235"
  become: yes

- name: Configure license slave
  command: "{{ splunk_home }}/bin/splunk edit licenser-localslave -master_uri '{{ splunk_lm_uri }}' -auth admin:{{ splunk_admin_pass }}"
  become: yes
  become_user: "{{ splunk_user }}"
  when: (splunk_lm_uri is defined)

- name: re-read facts after adding custom fact
  setup: filter=ansible_local
  become: yes

- include: upgrade-{{splunk_role}}.yml
  when: ( splunk_version > ansible_local.splunk.dp.version )
  become: yes

