---

- name: Restart Splunk
  command: "/etc/init.d/splunk-{{ splunkforwarder_role }} restart"
  become: yes

- name: Start Splunk
  service: name="splunk-{{ splunkforwarder_role }}" state=started
  become: yes

- name: Stop Splunk
  service: name="splunk-{{ splunkforwarder_role }}" state=stopped
  become: yes
