---
# Initial server setup.  Calls includes where needed.
#

- name: Install Git
  yum: name=git state=present

- name: Check mount point for base splunk dir
  shell: "grep {{ splunk_base }} /etc/fstab"
  register: mount
  ignore_errors: True

- include: setup_disks.yml
  when: mount|failed

- name: Check for splunk user
  shell: "grep splunk /etc/passwd"
  register: user
  ignore_errors: True

- include: setup_splunk_user.yml
  when: user|failed

