---
# This role contains inital server setup tasks such as:
# splunk user creation
# splunk_base checkout (.ssh and .bashrc, etc)
#

- name: Update Likewise user-ignore file if needed
  lineinfile: dest=/etc/pbis/user-ignore line=splunk state=present

- name: Create splunk OS user
  lineinfile: dest=/etc/passwd line="splunk:x:{{ splunk_uid }}:{{ splunk_gid }}:splunk:{{ splunk_base }}:/bin/bash" state=present backup=yes

- name: Create splunk OS group
  lineinfile: dest=/etc/group line="splunk:x:{{ splunk_gid }}:" state=present backup=yes

- name: Run pwconv
  command: /usr/sbin/pwconv

- name: Run grpconv
  command: /usr/sbin/grpconv

- name: Update splunk account expiry
  command: chage -I -1 -m 0 -M 99999 -E -1 splunk

- name: Set up authorized_keys for splunk
  authorized_key: user=splunk key="{{ item }}"
  with_file:
    - authorized_keys

- name: Chown splunk base
  file: dest={{ splunk_base }} owner=splunk group=splunk recurse=yes


