---
# Install the collectd agent
#
#

- name: Checkout Latest collectd Git Repo
  git: 
    repo: "{{ collectd_git_repo }}"
    dest: "{{ collectd_home }}" 
    ssh_opts: "-o StrictHostKeyChecking=no" 
    force: yes
    update: yes
    accept_hostkey: yes
  become: yes
  notify:
    - Enable collectd
    - Restart collectd

- name: Install collectd service
  copy:
    src: "{{ collectd_home }}/contrib/collectd.service"
    remote_src: no
    dest: "/etc/systemd/system/collectd.service"
    mode: 644
  become: yes
  register: collectd_update
  notify:
    - Reload systemd

- name: Chown shit
  file: 
    dest: "{{ collectd_home }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}" 
    recurse: yes
  become: yes

- name: Start collectd
  systemd:
    name: collectd
    state: started
  become: yes
  when: collectd_update.changed
