---
# Install the UF (opt splunk should already exist) 
#
#

- name: Check for existing /opt/splunk/uf that isn't a git managed install.
  stat: path="{{ splunk_home }}"
  register: uf_path
  become: true

- name: Stop splunk if running
  command: "{{ splunk_home }}/bin/splunk stop"
  ignore_errors: True
  when: uf_path.stat.isdir is defined
  become: true
  become_user: "{{ splunk_user }}"

- name: Remove old UF dir
  file: path={{ splunk_home }} state=absent
  when: uf_path.stat.isdir is defined
  become: yes

- name: Checkout Latest Splunk Forwarder from Git
  git: repo={{ splunk_git_repo }} dest={{ splunk_home }} ssh_opts="-o StrictHostKeyChecking=no" force=yes
  become: yes

- name: Chmod and Chown shit.
  file: dest={{ splunk_home }} owner={{ splunk_user }} group={{ splunk_group }} 
  become: yes

- name: Set web.conf configs
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/web.conf" 
    mode: 0650
    section: settings
    option: mgmtHostPort
    value: "0:{{splunkd_mgmt_port}}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: general
    option: serverName
    value: "{{ splunk_role }}-{{ inventory_hostname }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set Deployment Client Configs (1)
  ini_file: 
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: deployment-client
    option: clientName
    value: "{{ splunk_clientName }}"
    mode: 0650
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set Deployment Client Configs (2)
  ini_file: 
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: "target-broker:deploymentServer"
    option: targetUri
    value: "{{ ds_uri }}"
    mode: 0650
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy init script to init.d
  template: src=splunk_init dest="/etc/init.d/splunk-{{ splunk_role }}" mode=700
  become: yes

- name: Generate init symlinks
  command: "/sbin/chkconfig splunk-{{ splunk_role }} --add"
  become: yes

- name: Set UF init runlevels
  command: "/sbin/chkconfig splunk-{{ splunk_role }} on --level 235"
  become: yes

- name: Start Splunk
  command: "{{ splunk_home }}/bin/splunk start --accept-license --no-prompt --answer-yes"
  become: yes
  become_user: "{{ splunk_user }}"

- name: Set splunk uf admin password
  command: "{{ splunk_home }}/bin/splunk edit user admin -password {{ splunk_admin_pass }} -auth admin:changeme"
  become: yes
  become_user: "{{ splunk_user }}"

