---
# Install the UF (opt splunk should already exist) 
#
#

- name: Check for existing /opt/splunk/uf that isn't a git managed install.
  stat: path="{{ splunkforwarder_home }}"
  register: uf_path
  become: true

- name: Stop splunk if running
  command: "{{ splunkforwarder_home }}/bin/splunk stop"
  ignore_errors: True
  when: uf_path.stat.isdir is defined
  become: true
  become_user: "{{ splunkforwarder_user }}"

- name: Remove old UF dir
  file: path={{ splunkforwarder_home }} state=absent
  when: uf_path.stat.isdir is defined
  become: yes

- name: Checkout Latest Splunk Forwarder from Git
  git: repo={{ splunkforwarder_git_repo }} dest={{ splunkforwarder_home }} ssh_opts="-o StrictHostKeyChecking=no" force=yes
  become: yes
  become_user: "{{ splunkforwarder_user }}"

- name: Set web.conf configs
  ini_file:
    path: "{{ splunkforwarder_home }}/etc/system/local/web.conf" 
    mode: 0650
    section: settings
    option: mgmtHostPort
    value: "0:{{splunkd_mgmt_port}}"
    backup: yes
  become: yes
  become_user: "{{ splunkforwarder_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs
  ini_file:
    path: "{{ splunkforwarder_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: general
    option: serverName
    value: "{{ splunkforwarder_role }}-{{ inventory_hostname }}"
    backup: yes
  become: yes
  become_user: "{{ splunkforwarder_user }}"
  notify:
    - Restart Splunk

- name: Set Deployment Client Configs (1)
  ini_file: 
    path: "{{ splunkforwarder_home }}/etc/system/local/deploymentclient.conf"
    section: deployment-client
    option: clientName
    value: "{{ splunkforwarder_clientName }}"
    mode: 0650
    backup: yes
  become: yes
  become_user: "{{ splunkforwarder_user }}"
  notify:
    - Restart Splunk

- name: Set Deployment Client Configs (2)
  ini_file: 
    path: "{{ splunkforwarder_home }}/etc/system/local/deploymentclient.conf"
    section: "target-broker:deploymentServer"
    option: targetUri
    value: "{{ ds_uri }}"
    mode: 0650
    backup: yes
  become: yes
  become_user: "{{ splunkforwarder_user }}"
  notify:
    - Restart Splunk

- name: Copy init script to init.d
  template: src=splunk_init dest="/etc/init.d/splunk-{{ splunkforwarder_role }}" mode=700
  become: yes

- name: Generate init symlinks
  command: "/sbin/chkconfig splunk-{{ splunkforwarder_role }} --add"
  become: yes

- name: Set UF init runlevels
  command: "/sbin/chkconfig splunk-{{ splunkforwarder_role }} on --level 235"
  become: yes

- name: Start Splunk
  command: "{{ splunkforwarder_home }}/bin/splunk start --accept-license --no-prompt --answer-yes"
  become: yes
  become_user: "{{ splunkforwarder_user }}"

- name: Set splunk uf admin password
  command: "{{ splunkforwarder_home }}/bin/splunk edit user admin -password {{ splunkforwarder_admin_pass }} -auth admin:changeme"
  become: yes
  become_user: "{{ splunkforwarder_user }}"

