---
# Install the UF (opt splunk should already exist) 
#
#

- name: Check for existing UF repo.
  stat: path="{{ splunk_home }}/.git"
  register: st
  ignore_errors: True
  become: true

- name: Check if Splunk exists, but was never properly started (FTR still exists)
  stat: path="{{ splunk_home }}/ftr"
  register: ftr
  ignore_errors: True
  become: true

- include: install.yml
  when: ( st.stat.isdir is not defined or ftr.stat.islnk is defined )

- name: Ensure Splunk is started
  service: name="splunk-{{ splunk_role }}" state=started enabled=yes
  become: yes

- name: Ensure SPLUNK_OS_USER is set
  lineinfile: dest="{{ splunk_home }}/etc/splunk-launch.conf" 
              state=present 
              regexp="^SPLUNK_OS_USER="
              line="SPLUNK_OS_USER={{ splunk_user }}"
  become: true
  register: osuser
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy web.conf for splunk UF
  template: src=web.conf dest="{{ splunk_home }}/etc/system/local/web.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy server.conf for splunk UF
  template: src=server.conf dest="{{ splunk_home }}/etc/system/local/server.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Copy deploymentclient.conf
  template: src=deploymentclient.conf dest="{{ splunk_home }}/etc/system/local/deploymentclient.conf" mode=650
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk



