---
# Install the UF (opt splunk should already exist) 
#
#

- name: Check for existing UF repo.
  stat: path="{{ splunk_home }}/.git"
  register: st
  ignore_errors: True
  become: true

- name: Check if Splunk exists, but was never properly started (FTR still exists)
  stat: path="{{ splunk_home }}/ftr"
  register: ftr
  ignore_errors: True
  become: true

- include: install.yml
  when: ( st.stat.isdir is not defined or ftr.stat.islnk is defined )

- name: Ensure Splunk is started
  service: name="splunk-{{ splunk_role }}" state=started enabled=yes
  become: yes

- name: Ensure SPLUNK_OS_USER is set
  lineinfile: dest="{{ splunk_home }}/etc/splunk-launch.conf" 
              state=present 
              regexp="^SPLUNK_OS_USER="
              line="SPLUNK_OS_USER={{ splunk_user }}"
  become: true
  register: osuser
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set web.conf configs
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/web.conf" 
    mode: 0650
    section: settings
    option: mgmtHostPort
    value: "0:{{splunkd_mgmt_port}}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set server.conf configs
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf" 
    mode: 0650
    section: general
    option: serverName
    value: "{{ splunk_role }}-{{ inventory_hostname }}"
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set Deployment Client Configs (1)
  ini_file: 
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: deployment-client
    option: clientName
    value: "{{ splunk_clientName }}"
    mode: 0650
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk

- name: Set Deployment Client Configs (2)
  ini_file: 
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: "target-broker:deploymentServer"
    option: targetUri
    value: "{{ ds_uri }}"
    mode: 0650
    backup: yes
  become: yes
  become_user: "{{ splunk_user }}"
  notify:
    - Restart Splunk



