---
# Install the UF (opt splunk should already exist) 
#
# Should really change this to do a version check vs a hard down / checkout...should be simple with Git dumbass


- name: Ensure splunk is stopped prior to upgrade
  command: "{{ splunk_home }}/bin/splunk stop"
  ignore_errors: True
  become: true
  become_user: "{{ splunk_user }}"

- name: Chmod and Chown shit.
  file: dest={{ splunk_root }} owner={{ splunk_user }} group={{ splunk_group }} recurse=yes
  become: yes

- name: Copy web.conf for splunk UF
  template: src=web.conf dest="{{ splunk_home }}/etc/system/local/web.conf" mode=650
  become: true
  become_user: "{{ splunk_user }}"

- name: Copy deploymentclient.conf
  template: src=uf_deploymentclient.conf dest="{{ splunk_home }}/etc/system/local/deploymentclient.conf" mode=650
  become: true
  become_user: "{{ splunk_user }}"

- name: Start splunk uf
  command: "{{ splunk_home }}/bin/splunk start --accept-license --answer-yes"
  become: true
  become_user: "{{ splunk_user }}"

