---
# UF vars
splunk_version: 6.6.0
ds_uri: ip-172-31-7-21.ec2.internal:8089
splunk_role: uf
splunk_home: /opt/splunk/uf
splunk_root: /opt/splunk
splunkd_mgmt_port: 58089
splunk_git_repo: 'ssh://jslay@127.0.0.1:2222/Users/jslay/Projects/splunk/uf/linux/splunkforwarder'
splunk_admin_pass: '@thL0n64'
splunk_user: root
splunk_group: splunk
splunk_clientName: uf
