# splunk idx vars
splunk_version: 6.6.0
splunk_role: idx
splunk_web_enabled: 0
splunk_kvstore_disabled: 1
splunk_home: /opt/splunk/idx
splunk_root: /opt/splunk
splunkd_mgmt_port: 8089
splunk_git_repo: 'ssh://jslay@127.0.0.1:2222/Users/jslay/Projects/splunk/enterprise/linux/splunk'
splunk_admin_pass: '@thL0n64'
splunk_user: splunk
splunk_group: splunk
splunk_lm_uri: https://ip-172-31-33-197.ec2.internal:8089

# splunk idx cluster (If cluster_member is true, clustering.yml is included)
splunk_cluster_member: false
splunk_cluster_mode: slave
